services:
  cellnoor-api:
    image: ghcr.io/demhadais/cellnoor-api:latest
  cellnoor-ui:
    image: ghcr.io/demhadais/cellnoor-ui:latest
  caddy:
    environment:
      TLS_SETTINGS: /run/secrets/tls_certificate /run/secrets/tls_key
    secrets:
      - tls_certificate
      - tls_key
secrets:
  tls_certificate:
    file: ${CELLNOOR_TLS_CERTIFICATE_PATH}
  tls_key:
    file: ${CELLNOOR_TLS_KEY_PATH}
