// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthError } from "./AuthError";
import type { DataValidationError } from "./DataValidationError";
import type { DatabaseError } from "./DatabaseError";

export type ApiErrorResponse = { status: number, } & ({ "type": "auth", "info": AuthError } | { "type": "data", "info": DataValidationError } | { "type": "database", "info": DatabaseError } | { "type": "malformed_request", "info": { message: string, } } | { "type": "other" });
