// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryType } from "./LibraryType";
import type { NonEmptyString } from "./NonEmptyString";
import type { NonEmptyVec } from "./NonEmptyVec";
import type { JsonValue } from "./serde_json/JsonValue";

export type CdnaCreation = { prepared_at: string, n_amplification_cycles: number, volume_µl: number, preparer_ids: NonEmptyVec<string>, library_type: LibraryType, readable_id: NonEmptyString, gem_pool_id?: string, additional_data?: JsonValue, };
