// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GemPoolSummary } from "./GemPoolSummary";
import type { LibraryType } from "./LibraryType";
import type { NonEmptyString } from "./NonEmptyString";
import type { JsonValue } from "./serde_json/JsonValue";

export type Cdna = { gem_pool: GemPoolSummary, id: string, prepared_at: string, n_amplification_cycles: number, library_type: LibraryType, readable_id: NonEmptyString, gem_pool_id?: string, additional_data?: JsonValue, };
