// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CdnaQuery = { filter?: { ids?: Array<string>, }, limit?: bigint, offset?: bigint, order_by?: Array<{ "id": { descending?: boolean, } } | { "readable_id": { descending?: boolean, } } | { "library_type": { descending?: boolean, } } | { "prepared_at": { descending?: boolean, } } | { "gem_pool_id": { descending?: boolean, } } | { "n_amplification_cycles": { descending?: boolean, } }>, };
