// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Links } from "./Links";
import type { NonEmptyString } from "./NonEmptyString";
import type { TenxAssay } from "./TenxAssay";

export type ChromiumDatasetSummary = { id: string, links: Links, delivered_at: string, assay: TenxAssay, name: NonEmptyString, lab_id: string, };
