// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecimenFilter } from "./SpecimenFilter";
import type { TenxAssayFilter } from "./TenxAssayFilter";

export type ChromiumDatasetQuery = { filter?: { ids?: Array<string>, names?: Array<string>, specimen?: SpecimenFilter, assay?: TenxAssayFilter, lab_ids?: Array<string>, delivered_before?: string, delivered_after?: string, }, limit?: bigint, offset?: bigint, order_by?: Array<{ "id": { descending?: boolean, } } | { "name": { descending?: boolean, } } | { "lab_id": { descending?: boolean, } } | { "delivered_at": { descending?: boolean, } }>, };
