// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChromiumDatasetCmdline = "cellranger-arc count" | "cellranger-atac count" | "cellranger count" | "cellranger multi" | "cellranger vdj";
