// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChromiumDatasetCmdline } from "./ChromiumDatasetCmdline";
import type { NonEmptyString } from "./NonEmptyString";

export type ChromiumDatasetCreation = { delivered_at: string, library_ids: Array<string>, cmdline: ChromiumDatasetCmdline, name: NonEmptyString, lab_id: string, };
