// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CountingMethod = "bright_field" | "acridine_orange_propidium_iodide" | "trypan_blue";
