// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DatabaseError = { "type": "resource_not_found", "info": { resource: string, resource_id: string, } } | { "type": "data", "info": { message: string, } } | { "type": "duplicate_resource", "info": { resource: string, fields: Array<string>, values: Array<string>, } } | { "type": "invalid_reference", "info": { resource: string, referenced_resource: string, value: string | null, } } | { "type": "other", "info": { message: string, } };
