// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixedBlockEmbeddingMatrix } from "./FixedBlockEmbeddingMatrix";
import type { FrozenBlockEmbeddingMatrix } from "./FrozenBlockEmbeddingMatrix";

export type EmbeddingMatrix = FixedBlockEmbeddingMatrix | FrozenBlockEmbeddingMatrix;
