// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockFixative } from "./BlockFixative";
import type { SuspensionFixative } from "./SuspensionFixative";
import type { TissueFixative } from "./TissueFixative";

export type Fixative = BlockFixative | SuspensionFixative | TissueFixative;
