// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyString } from "./NonEmptyString";

export type GemPoolSummary = { id: string, chromium_run_id: string, readable_id: NonEmptyString, };
