// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InitialDataValidationError = { "type": "app_admin_without_microsoft_entra_oid" } | { "type": "non10x_genomics_url", "info": string };
