// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Links } from "./Links";
import type { NonEmptyString } from "./NonEmptyString";
import type { PersonSummary } from "./PersonSummary";

export type Lab = { pi: PersonSummary, id: string, links: Links, name: NonEmptyString, pi_id: string, delivery_dir: NonEmptyString, };
