// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyString } from "./NonEmptyString";

export type LabCreation = { name: NonEmptyString, pi_id: string, delivery_dir: NonEmptyString, };
