// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LabValidationError = { "type": "delivery_dir", "info": { delivery_dir: string, message: string, } };
