// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryType } from "./LibraryType";

export type LibraryValidationError = { "type": "volume", "info": { library_type: LibraryType, expected: number, found: number, } } | { "type": "index_set", "info": { expected: string, found: string | null, } };
