// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CdnaSummary } from "./CdnaSummary";
import type { Links } from "./Links";
import type { NonEmptyString } from "./NonEmptyString";
import type { JsonValue } from "./serde_json/JsonValue";

export type Library = { cdna: CdnaSummary, id: string, links: Links, number_of_sample_index_pcr_cycles: number, target_reads_per_cell: bigint, prepared_at: string, readable_id: NonEmptyString, cdna_id: string, single_index_set_name?: NonEmptyString, dual_index_set_name?: NonEmptyString, additional_data?: JsonValue, };
