// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyString } from "./NonEmptyString";
import type { NonEmptyVec } from "./NonEmptyVec";
import type { RangedU16 } from "./RangedU16";
import type { RangedU32 } from "./RangedU32";
import type { JsonValue } from "./serde_json/JsonValue";

export type LibraryCreation = { number_of_sample_index_pcr_cycles: RangedU16, volume_µl: number, target_reads_per_cell: RangedU32, prepared_at: string, preparer_ids: NonEmptyVec<string>, readable_id: NonEmptyString, cdna_id: string, single_index_set_name?: NonEmptyString, dual_index_set_name?: NonEmptyString, additional_data?: JsonValue, };
