// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NucleicAcidMeasurementError = { "type": "electrophoretic_measurement_sizing_range", "info": { min: number, max: number, } };
