// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyString } from "./NonEmptyString";
import type { UserRole } from "./UserRole";

export type PersonCreation = { email: NonEmptyString, roles: Array<UserRole>, name: NonEmptyString, orcid?: NonEmptyString, institution_id: string, microsoft_entra_oid?: string, };
