// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Links } from "./Links";
import type { NonEmptyString } from "./NonEmptyString";

export type PersonSummary = { id: string, email?: string, email_verified: boolean, links: Links, name: NonEmptyString, orcid?: NonEmptyString, institution_id: string, microsoft_entra_oid?: string, };
