// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Institution } from "./Institution";
import type { Links } from "./Links";
import type { NonEmptyString } from "./NonEmptyString";
import type { UserRole } from "./UserRole";

export type Person = { roles: Array<UserRole>, institution: Institution, id: string, email?: string, email_verified: boolean, links: Links, name: NonEmptyString, orcid?: NonEmptyString, institution_id: string, microsoft_entra_oid?: string, };
