// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyString } from "./NonEmptyString";
import type { JsonValue } from "./serde_json/JsonValue";

export type SequencingRunCreation = { begun_at: string, finished_at?: string, readable_id: NonEmptyString, additional_data?: JsonValue, };
