// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyString } from "./NonEmptyString";
import type { RangedF32 } from "./RangedF32";

export type SpecimenMeasurementData = { "DV200": { instrument_name?: NonEmptyString, value: RangedF32, } } | { "RIN": { instrument_name?: NonEmptyString, value: RangedF32, } };
