// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddingMatrix } from "./EmbeddingMatrix";
import type { Fixative } from "./Fixative";
import type { LabSummary } from "./LabSummary";
import type { Links } from "./Links";
import type { NonEmptyString } from "./NonEmptyString";
import type { PersonSummary } from "./PersonSummary";
import type { Species } from "./Species";
import type { SpecimenType } from "./SpecimenType";
import type { JsonValue } from "./serde_json/JsonValue";

export type Specimen = { lab: LabSummary, submitted_by: PersonSummary, id: string, links: Links, readable_id: NonEmptyString, name: NonEmptyString, submitted_by: string, received_at: string, lab_id: string, species: Species, host_species?: Species, returned_by?: string, returned_at?: string, tissue: NonEmptyString, additional_data?: JsonValue, type_: SpecimenType, embedded_in?: EmbeddingMatrix, fixative?: Fixative, frozen: boolean, cryopreserved: boolean, };
