// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Species } from "./Species";

export type SpecimenValidationError = { "type": "same_donor_and_host_species", "info": { species: Species, } } | { "type": "returned_before_received", "info": { received_at: string, returned_at: string, } };
