// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecimenMeasurementData } from "./SpecimenMeasurementData";

export type SpecimenMeasurement = { id: string, specimen_id: string, measured_by: string, measured_at: string, data: SpecimenMeasurementData, };
