// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyString } from "./NonEmptyString";
import type { NonEmptyVec } from "./NonEmptyVec";
import type { SuspensionTagging } from "./SuspensionTagging";
import type { JsonValue } from "./serde_json/JsonValue";

export type SuspensionPoolCreation = { preparer_ids: NonEmptyVec<string>, suspensions: NonEmptyVec<SuspensionTagging>, readable_id: NonEmptyString, name: NonEmptyString, pooled_at: string, additional_data?: JsonValue, };
