// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Links } from "./Links";
import type { NonEmptyString } from "./NonEmptyString";
import type { JsonValue } from "./serde_json/JsonValue";

export type SuspensionPool = { id: string, links: Links, readable_id: NonEmptyString, name: NonEmptyString, pooled_at: string, additional_data?: JsonValue, };
