// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SuspensionValidationError = { "type": "created_before_specimen_received", "info": { created_at: string, specimen_received_at: string, } };
