// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SuspensionQuery = { filter?: { ids?: Array<string>, }, limit?: bigint, offset?: bigint, order_by?: Array<{ "id": { descending?: boolean, } } | { "readable_id": { descending?: boolean, } } | { "parent_specimen_id": { descending?: boolean, } } | { "created_at": { descending?: boolean, } } | { "lysis_duration_minutes": { descending?: boolean, } } | { "target_cell_recovery": { descending?: boolean, } }>, };
