// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuspensionMeasurementData } from "./SuspensionMeasurementData";

export type SuspensionMeasurementFields = { measured_by: string, measured_at: string, data: SuspensionMeasurementData, };
