// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Links } from "./Links";
import type { NonEmptyString } from "./NonEmptyString";
import type { SpecimenSummary } from "./SpecimenSummary";
import type { SuspensionContent } from "./SuspensionContent";
import type { JsonValue } from "./serde_json/JsonValue";

export type Suspension = { parent_specimen: SpecimenSummary, id: string, created_at?: string, target_cell_recovery: bigint, lysis_duration_minutes?: number, content: SuspensionContent, links: Links, readable_id: NonEmptyString, parent_specimen_id: string, additional_data?: JsonValue, };
