// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SuspensionPoolQuery = { filter?: { ids?: Array<string>, }, limit?: bigint, offset?: bigint, order_by?: Array<{ "id": { descending?: boolean, } } | { "readable_id": { descending?: boolean, } } | { "name": { descending?: boolean, } } | { "pooled_at": { descending?: boolean, } }>, };
