// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuspensionPoolMeasurementData } from "./SuspensionPoolMeasurementData";

export type SuspensionPoolMeasurement = { id: string, pool_id: string, measured_by: string, measured_at: string, data: SuspensionPoolMeasurementData, };
