// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryType } from "./LibraryType";
import type { SampleMultiplexing } from "./SampleMultiplexing";

export type TenxAssayFilter = { ids?: Array<string>, names?: Array<string>, library_types?: Array<Array<LibraryType>>, sample_multiplexing?: Array<SampleMultiplexing>, chemistry_versions?: Array<string>, chromium_chips?: Array<string>, };
