// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryType } from "./LibraryType";
import type { Links } from "./Links";
import type { SampleMultiplexing } from "./SampleMultiplexing";

export type TenxAssay = { id: string, links: Links, name: string, library_types?: Array<LibraryType | null>, sample_multiplexing?: SampleMultiplexing, chemistry_version: string, protocol_url: string, chromium_chip?: string, cmdlines?: Array<string | null>, };
