// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RangedF32 } from "./RangedF32";

export type Viability = { value: RangedF32, };
